version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: cypher-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cypher
      POSTGRES_PASSWORD: cypher
      TZ: "Asia/Tokyo"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
