name: ci

on: push

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Static code analysis
        run: ./gradlew detekt test
